# 3 - Tipos e Conversão de tipos
O Numpy suporta uma variedade de tipos muito maior do que o Python.

Existem 5 tipos básicos numéricos
- Booleans (bool)
- Integers (int)
- Unsigned Intergers (uint)
- Floating Points (float)
- Complex

Complementarmente, a célula abaixo mostra um quadro comparativos com uma maior quantidade de tipos do Numpy.

![datatypes.png](attachment:datatypes.png)

In [ ]:
import numpy as np

float com 32 bits

In [ ]:
x = np.float32(1.0)
x

1.0

array de inteiros

In [ ]:
y = np.int_([1,2,4])
y

array([1, 2, 4])

Retorna valores dentro de um intervalo x do tipo unsigned int com 8 bits

In [ ]:
z = np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

In [ ]:
np.array([1, 2, 3], dtype='f')

array([1., 2., 3.], dtype=float32)

## Convertendo tipos de arrays

Para convertermos arrays Numpy, basta utilizarmos o método astype().

In [ ]:
z.astype(float)

array([0., 1., 2.])

In [ ]:
np.int8(z)

array([0, 1, 2], dtype=int8)

Para verificarmos o tipo de um array Numpy, basta verificarmos o seu atributo dtype.

In [ ]:
z.dtype

dtype('uint8')